package org.icgc.dcc.release.job.annotate.model;

import lombok.Value;
import lombok.Builder;

/**
 * Represents a record in the ssm_s.txt or sgv_s.txt file.<br>
 * <b>Note:</b> in the sgv_s.txt file some fields have different names. I.e. {@code aa_mutation} -> {@code aa_change},
 * {@code cds_mutation} -> {@code cds_change}.
 */
@Value
@Builder
public class SecondaryEntity {

  String consequenceType;
  String aaMutation;
  String cdsMutation;

  // proteinDomainAffected is not currently used, because information about affected domain is generated by some other
  // tool than snpEff
  String proteinDomainAffected;
  String geneAffected;
  String transcriptAffected;
  String geneBuildVersion;
  String note;
  String observationId;

}
